### PR TITLE
rm and unlink empty pages

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by rkdarst** [comment]
What if we, to make the lesson self-demonstrating, add a text on these pages that says "there is no content here, but it would say [topic] in an actual lesson.  The empty page is left here to demonstrate our goal for lessons."

**Comment by rkdarst** [comment]
#18 is an alternative solution

**Comment by johanhellsvik** [comment]
I have merged #18

**Comment by bast** [comment]
Good idea. Closing.

**Pull request closed without merging**
